// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AITS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103201823_AddSessionTypeManagement")]
    partial class AddSessionTypeManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EnumType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EnumTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TherapyType"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SessionStatus"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PaymentStatus"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SessionTranscriptionSource"
                        });
                });

            modelBuilder.Entity("EnumValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EnumTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnumTypeId", "Code")
                        .IsUnique();

                    b.ToTable("EnumValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CBT",
                            EnumTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "DBT",
                            EnumTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "ACT",
                            EnumTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "Scheduled",
                            EnumTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "Confirmed",
                            EnumTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "Completed",
                            EnumTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "Cancelled",
                            EnumTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "Pending",
                            EnumTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "Completed",
                            EnumTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "Failed",
                            EnumTypeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "ManualText",
                            EnumTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Code = "TextFile",
                            EnumTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Code = "AudioRecording",
                            EnumTypeId = 4
                        },
                        new
                        {
                            Id = 14,
                            Code = "AudioUpload",
                            EnumTypeId = 4
                        });
                });

            modelBuilder.Entity("EnumValueTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EnumValueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnumValueId", "Culture")
                        .IsUnique();

                    b.ToTable("EnumValueTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "pl",
                            EnumValueId = 1,
                            Name = "Terapia poznawczo-behawioralna"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en",
                            EnumValueId = 1,
                            Name = "Cognitive Behavioral Therapy"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "pl",
                            EnumValueId = 2,
                            Name = "Dialektyczna terapia behawioralna"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "en",
                            EnumValueId = 2,
                            Name = "Dialectical Behavior Therapy"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "pl",
                            EnumValueId = 3,
                            Name = "Terapia akceptacji i zaangażowania"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "en",
                            EnumValueId = 3,
                            Name = "Acceptance and Commitment Therapy"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "pl",
                            EnumValueId = 4,
                            Name = "Zaplanowana"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "en",
                            EnumValueId = 4,
                            Name = "Scheduled"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "pl",
                            EnumValueId = 5,
                            Name = "Potwierdzona"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "en",
                            EnumValueId = 5,
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "pl",
                            EnumValueId = 6,
                            Name = "Zakończona"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "en",
                            EnumValueId = 6,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "pl",
                            EnumValueId = 7,
                            Name = "Anulowana"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "en",
                            EnumValueId = 7,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "pl",
                            EnumValueId = 8,
                            Name = "Oczekująca"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "en",
                            EnumValueId = 8,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "pl",
                            EnumValueId = 9,
                            Name = "Zrealizowana"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "en",
                            EnumValueId = 9,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "pl",
                            EnumValueId = 10,
                            Name = "Nieudana"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "en",
                            EnumValueId = 10,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "pl",
                            EnumValueId = 11,
                            Name = "Tekst ręczny"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "en",
                            EnumValueId = 11,
                            Name = "Manual text"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "pl",
                            EnumValueId = 12,
                            Name = "Plik tekstowy"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "en",
                            EnumValueId = 12,
                            Name = "Text file"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "pl",
                            EnumValueId = 13,
                            Name = "Nagranie audio"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "en",
                            EnumValueId = 13,
                            Name = "Audio recording"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "pl",
                            EnumValueId = 14,
                            Name = "Załadowany plik audio"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "en",
                            EnumValueId = 14,
                            Name = "Uploaded audio file"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("Pesel");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TpayTransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("TpayTransactionId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMeetLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SessionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TerapeutaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SessionTypeId");

                    b.HasIndex("StartDateTime");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("SessionTranscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionTranscription", (string)null);
                });

            modelBuilder.Entity("SessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SessionType", (string)null);
                });

            modelBuilder.Entity("SessionTypeQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTypeId", "DisplayOrder");

                    b.ToTable("SessionTypeQuestion", (string)null);
                });

            modelBuilder.Entity("SessionTypeTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTypeId", "DisplayOrder");

                    b.ToTable("SessionTypeTip", (string)null);
                });

            modelBuilder.Entity("TherapistGoogleToken", b =>
                {
                    b.Property<string>("TerapeutaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TerapeutaId");

                    b.ToTable("TherapistGoogleTokens");
                });

            modelBuilder.Entity("Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Culture")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "pl",
                            Key = "login.title",
                            Value = "Logowanie"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en",
                            Key = "login.title",
                            Value = "Sign in"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "pl",
                            Key = "login.email",
                            Value = "E-mail"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "en",
                            Key = "login.email",
                            Value = "Email"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "pl",
                            Key = "login.password",
                            Value = "Hasło"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "en",
                            Key = "login.password",
                            Value = "Password"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "pl",
                            Key = "login.submit",
                            Value = "Zaloguj"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "en",
                            Key = "login.submit",
                            Value = "Log in"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "pl",
                            Key = "login.language",
                            Value = "Język"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "en",
                            Key = "login.language",
                            Value = "Language"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "pl",
                            Key = "dashboard.title",
                            Value = "Kokpit"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "en",
                            Key = "dashboard.title",
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "pl",
                            Key = "dashboard.todaySessions",
                            Value = "Dzisiejsze sesje"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "en",
                            Key = "dashboard.todaySessions",
                            Value = "Today's sessions"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "pl",
                            Key = "dashboard.allSessions",
                            Value = "Wszystkie sesje"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "en",
                            Key = "dashboard.allSessions",
                            Value = "All sessions"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "pl",
                            Key = "dashboard.statistics",
                            Value = "Statystyki"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "en",
                            Key = "dashboard.statistics",
                            Value = "Statistics"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "pl",
                            Key = "dashboard.sessionsToday",
                            Value = "Sesje dzisiaj"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "en",
                            Key = "dashboard.sessionsToday",
                            Value = "Sessions today"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "pl",
                            Key = "dashboard.sessionsScheduled",
                            Value = "Zaplanowane"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "en",
                            Key = "dashboard.sessionsScheduled",
                            Value = "Scheduled"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "pl",
                            Key = "dashboard.sessionsCompleted",
                            Value = "Zakończone w tym miesiącu"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "en",
                            Key = "dashboard.sessionsCompleted",
                            Value = "Completed this month"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "pl",
                            Key = "sessions.title",
                            Value = "Sesje"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "en",
                            Key = "sessions.title",
                            Value = "Sessions"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "pl",
                            Key = "sessions.new",
                            Value = "Nowa sesja"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "en",
                            Key = "sessions.new",
                            Value = "New session"
                        },
                        new
                        {
                            Id = 29,
                            Culture = "pl",
                            Key = "sessions.edit",
                            Value = "Edytuj sesję"
                        },
                        new
                        {
                            Id = 30,
                            Culture = "en",
                            Key = "sessions.edit",
                            Value = "Edit session"
                        },
                        new
                        {
                            Id = 31,
                            Culture = "pl",
                            Key = "sessions.details",
                            Value = "Szczegóły sesji"
                        },
                        new
                        {
                            Id = 32,
                            Culture = "en",
                            Key = "sessions.details",
                            Value = "Session details"
                        },
                        new
                        {
                            Id = 33,
                            Culture = "pl",
                            Key = "sessions.patient",
                            Value = "Pacjent"
                        },
                        new
                        {
                            Id = 34,
                            Culture = "en",
                            Key = "sessions.patient",
                            Value = "Patient"
                        },
                        new
                        {
                            Id = 35,
                            Culture = "pl",
                            Key = "sessions.startTime",
                            Value = "Data rozpoczęcia"
                        },
                        new
                        {
                            Id = 36,
                            Culture = "en",
                            Key = "sessions.startTime",
                            Value = "Start time"
                        },
                        new
                        {
                            Id = 37,
                            Culture = "pl",
                            Key = "sessions.endTime",
                            Value = "Data zakończenia"
                        },
                        new
                        {
                            Id = 38,
                            Culture = "en",
                            Key = "sessions.endTime",
                            Value = "End time"
                        },
                        new
                        {
                            Id = 39,
                            Culture = "pl",
                            Key = "sessions.price",
                            Value = "Cena"
                        },
                        new
                        {
                            Id = 40,
                            Culture = "en",
                            Key = "sessions.price",
                            Value = "Price"
                        },
                        new
                        {
                            Id = 41,
                            Culture = "pl",
                            Key = "sessions.status",
                            Value = "Status"
                        },
                        new
                        {
                            Id = 42,
                            Culture = "en",
                            Key = "sessions.status",
                            Value = "Status"
                        },
                        new
                        {
                            Id = 43,
                            Culture = "pl",
                            Key = "sessions.confirm",
                            Value = "Potwierdź"
                        },
                        new
                        {
                            Id = 44,
                            Culture = "en",
                            Key = "sessions.confirm",
                            Value = "Confirm"
                        },
                        new
                        {
                            Id = 45,
                            Culture = "pl",
                            Key = "sessions.cancel",
                            Value = "Anuluj"
                        },
                        new
                        {
                            Id = 46,
                            Culture = "en",
                            Key = "sessions.cancel",
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = 47,
                            Culture = "pl",
                            Key = "sessions.sendNotification",
                            Value = "Wyślij powiadomienie"
                        },
                        new
                        {
                            Id = 48,
                            Culture = "en",
                            Key = "sessions.sendNotification",
                            Value = "Send notification"
                        },
                        new
                        {
                            Id = 49,
                            Culture = "pl",
                            Key = "sessions.googleMeet",
                            Value = "Link Google Meet"
                        },
                        new
                        {
                            Id = 50,
                            Culture = "en",
                            Key = "sessions.googleMeet",
                            Value = "Google Meet link"
                        },
                        new
                        {
                            Id = 51,
                            Culture = "pl",
                            Key = "sessions.notes",
                            Value = "Notatki"
                        },
                        new
                        {
                            Id = 52,
                            Culture = "en",
                            Key = "sessions.notes",
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 53,
                            Culture = "pl",
                            Key = "sessions.save",
                            Value = "Zapisz"
                        },
                        new
                        {
                            Id = 54,
                            Culture = "en",
                            Key = "sessions.save",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 55,
                            Culture = "pl",
                            Key = "sessions.delete",
                            Value = "Usuń"
                        },
                        new
                        {
                            Id = 56,
                            Culture = "en",
                            Key = "sessions.delete",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 57,
                            Culture = "pl",
                            Key = "patients.title",
                            Value = "Pacjenci"
                        },
                        new
                        {
                            Id = 58,
                            Culture = "en",
                            Key = "patients.title",
                            Value = "Patients"
                        },
                        new
                        {
                            Id = 59,
                            Culture = "pl",
                            Key = "patients.new",
                            Value = "Nowy pacjent"
                        },
                        new
                        {
                            Id = 60,
                            Culture = "en",
                            Key = "patients.new",
                            Value = "New patient"
                        },
                        new
                        {
                            Id = 61,
                            Culture = "pl",
                            Key = "patients.edit",
                            Value = "Edytuj pacjenta"
                        },
                        new
                        {
                            Id = 62,
                            Culture = "en",
                            Key = "patients.edit",
                            Value = "Edit patient"
                        },
                        new
                        {
                            Id = 63,
                            Culture = "pl",
                            Key = "patients.firstName",
                            Value = "Imię"
                        },
                        new
                        {
                            Id = 64,
                            Culture = "en",
                            Key = "patients.firstName",
                            Value = "First name"
                        },
                        new
                        {
                            Id = 65,
                            Culture = "pl",
                            Key = "patients.lastName",
                            Value = "Nazwisko"
                        },
                        new
                        {
                            Id = 66,
                            Culture = "en",
                            Key = "patients.lastName",
                            Value = "Last name"
                        },
                        new
                        {
                            Id = 67,
                            Culture = "pl",
                            Key = "patients.email",
                            Value = "E-mail"
                        },
                        new
                        {
                            Id = 68,
                            Culture = "en",
                            Key = "patients.email",
                            Value = "Email"
                        },
                        new
                        {
                            Id = 69,
                            Culture = "pl",
                            Key = "patients.phone",
                            Value = "Telefon"
                        },
                        new
                        {
                            Id = 70,
                            Culture = "en",
                            Key = "patients.phone",
                            Value = "Phone"
                        },
                        new
                        {
                            Id = 71,
                            Culture = "pl",
                            Key = "patients.notes",
                            Value = "Notatki"
                        },
                        new
                        {
                            Id = 72,
                            Culture = "en",
                            Key = "patients.notes",
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 87,
                            Culture = "pl",
                            Key = "patients.dateOfBirth",
                            Value = "Data urodzenia"
                        },
                        new
                        {
                            Id = 88,
                            Culture = "en",
                            Key = "patients.dateOfBirth",
                            Value = "Date of birth"
                        },
                        new
                        {
                            Id = 89,
                            Culture = "pl",
                            Key = "patients.gender",
                            Value = "Płeć"
                        },
                        new
                        {
                            Id = 90,
                            Culture = "en",
                            Key = "patients.gender",
                            Value = "Gender"
                        },
                        new
                        {
                            Id = 91,
                            Culture = "pl",
                            Key = "patients.pesel",
                            Value = "PESEL"
                        },
                        new
                        {
                            Id = 92,
                            Culture = "en",
                            Key = "patients.pesel",
                            Value = "PESEL"
                        },
                        new
                        {
                            Id = 93,
                            Culture = "pl",
                            Key = "patients.street",
                            Value = "Ulica"
                        },
                        new
                        {
                            Id = 94,
                            Culture = "en",
                            Key = "patients.street",
                            Value = "Street"
                        },
                        new
                        {
                            Id = 95,
                            Culture = "pl",
                            Key = "patients.streetNumber",
                            Value = "Numer"
                        },
                        new
                        {
                            Id = 96,
                            Culture = "en",
                            Key = "patients.streetNumber",
                            Value = "Number"
                        },
                        new
                        {
                            Id = 97,
                            Culture = "pl",
                            Key = "patients.apartmentNumber",
                            Value = "Nr lokalu"
                        },
                        new
                        {
                            Id = 98,
                            Culture = "en",
                            Key = "patients.apartmentNumber",
                            Value = "Apartment"
                        },
                        new
                        {
                            Id = 99,
                            Culture = "pl",
                            Key = "patients.city",
                            Value = "Miasto"
                        },
                        new
                        {
                            Id = 100,
                            Culture = "en",
                            Key = "patients.city",
                            Value = "City"
                        },
                        new
                        {
                            Id = 101,
                            Culture = "pl",
                            Key = "patients.postalCode",
                            Value = "Kod pocztowy"
                        },
                        new
                        {
                            Id = 102,
                            Culture = "en",
                            Key = "patients.postalCode",
                            Value = "Postal code"
                        },
                        new
                        {
                            Id = 103,
                            Culture = "pl",
                            Key = "patients.country",
                            Value = "Kraj"
                        },
                        new
                        {
                            Id = 104,
                            Culture = "en",
                            Key = "patients.country",
                            Value = "Country"
                        },
                        new
                        {
                            Id = 73,
                            Culture = "pl",
                            Key = "payments.title",
                            Value = "Płatności"
                        },
                        new
                        {
                            Id = 74,
                            Culture = "en",
                            Key = "payments.title",
                            Value = "Payments"
                        },
                        new
                        {
                            Id = 75,
                            Culture = "pl",
                            Key = "payments.create",
                            Value = "Utwórz płatność"
                        },
                        new
                        {
                            Id = 76,
                            Culture = "en",
                            Key = "payments.create",
                            Value = "Create payment"
                        },
                        new
                        {
                            Id = 77,
                            Culture = "pl",
                            Key = "payments.amount",
                            Value = "Kwota"
                        },
                        new
                        {
                            Id = 78,
                            Culture = "en",
                            Key = "payments.amount",
                            Value = "Amount"
                        },
                        new
                        {
                            Id = 79,
                            Culture = "pl",
                            Key = "payments.pay",
                            Value = "Zapłać"
                        },
                        new
                        {
                            Id = 80,
                            Culture = "en",
                            Key = "payments.pay",
                            Value = "Pay"
                        },
                        new
                        {
                            Id = 81,
                            Culture = "pl",
                            Key = "sms.session.confirmed",
                            Value = "Sesja potwierdzona na {date} o {time}. Link do spotkania: {link}"
                        },
                        new
                        {
                            Id = 82,
                            Culture = "en",
                            Key = "sms.session.confirmed",
                            Value = "Session confirmed on {date} at {time}. Meeting link: {link}"
                        },
                        new
                        {
                            Id = 83,
                            Culture = "pl",
                            Key = "sms.session.changed",
                            Value = "Sesja została zmieniona. Nowa data: {date} o {time}. Link: {link}"
                        },
                        new
                        {
                            Id = 84,
                            Culture = "en",
                            Key = "sms.session.changed",
                            Value = "Session has been changed. New date: {date} at {time}. Link: {link}"
                        },
                        new
                        {
                            Id = 85,
                            Culture = "pl",
                            Key = "sms.session.cancelled",
                            Value = "Sesja na {date} została anulowana."
                        },
                        new
                        {
                            Id = 86,
                            Culture = "en",
                            Key = "sms.session.cancelled",
                            Value = "Session on {date} has been cancelled."
                        });
                });

            modelBuilder.Entity("EnumValue", b =>
                {
                    b.HasOne("EnumType", "EnumType")
                        .WithMany()
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumType");
                });

            modelBuilder.Entity("EnumValueTranslation", b =>
                {
                    b.HasOne("EnumValue", "EnumValue")
                        .WithMany()
                        .HasForeignKey("EnumValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumValue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("Session", "Session")
                        .WithOne("Payment")
                        .HasForeignKey("Payment", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany("Sessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SessionType", "SessionType")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApplicationUser", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SessionType");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("SessionTranscription", b =>
                {
                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Session", "Session")
                        .WithMany("Transcriptions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionTypeQuestion", b =>
                {
                    b.HasOne("SessionType", "SessionType")
                        .WithMany("Questions")
                        .HasForeignKey("SessionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionType");
                });

            modelBuilder.Entity("SessionTypeTip", b =>
                {
                    b.HasOne("SessionType", "SessionType")
                        .WithMany("Tips")
                        .HasForeignKey("SessionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionType");
                });

            modelBuilder.Entity("TherapistGoogleToken", b =>
                {
                    b.HasOne("ApplicationUser", "Terapeuta")
                        .WithOne()
                        .HasForeignKey("TherapistGoogleToken", "TerapeutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Transcriptions");
                });

            modelBuilder.Entity("SessionType", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sessions");

                    b.Navigation("Tips");
                });
#pragma warning restore 612, 618
        }
    }
}
